### ISSUE TITLE
not work with third person melee

### ISSUE THREAD

**Issue by alpezaxxx** [wesleywh/InvectorPhotonPUNMultiplayerAddon#1]
can you update this for melee ? not for shooter

when i import this i got 20 errors 

when i join lobby and create room.. i cant see other players ?

**Comment by wesleywh** [comment]
You bet. You're very correct with saying this doesnt work for melee. I
haven't ported it to work with the melee only template quite yet. This is
on the roadmap to do.

**Comment by wesleywh** [comment]
I have added a MeleeOnly package to the 0.2.0 release. Note this is still very much a work in progress so some animations are not quite cleanly being synced yet.
